FROM node:12-alpine
# Create app directory inside docker file
WORKDIR /usr/src/app
COPY package*.json ./
# Bundle app source code
COPY . .
RUN npm install --silent
EXPOSE 8080
CMD [ "npm", "run", "serve" ]