version: '2'
volumes:
  database:
    external: true
services:
    client:
        build: 
          context: ./client
        ports:
        - "8080:8080"
        depends_on:
        - server
        container_name: DSS_UI
    server:
      build: 
        context: ./server
      ports:
        - "8081:8081"
      volumes:
        - database:/usr/src/app/db
      container_name: DSS_API